version: '3.4'

networks:
  internal:

services:
  rabbit:
    command:
      - rabbitmq-server
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - 8080:15672/tcp
      - 5672:5672/tcp
    networks:
      - internal
  saphub.apiendpoint:
    image: ${DOCKER_REGISTRY-}saphubapiendpoint
    hostname: saphubapi
    build:
      context: .
      dockerfile: src/SAPHub.ApiEndpoint/Dockerfile
    environment:
      - SAPHUB_BUS__TYPE=rabbitmq
      - SAPHUB_BUS__CONNECTIONSTRING=amqp://guest:guest@rabbit
      - SAPHUB_ENDPOINTS__default=http://localhost
      - SAPHUB_ENDPOINTS__api=http://saphubapi
      - SAPHUB_ENDPOINTS__ui=http://localhost:5000
    ports:
      - 5001:80
    depends_on:
      - rabbit
    networks:
      - internal

  saphub.ui:
    image: ${DOCKER_REGISTRY-}saphubui
    hostname: saphubui
    build:
      context: .
      dockerfile: src/SAPHub.UI/Dockerfile
    networks:
      - internal
    environment:
      - SAPHUB_ENDPOINTS__default=http://localhost
      - SAPHUB_ENDPOINTS__api=http://localhost:5001
      - SAPHUB_ENDPOINTS__ui=http://saphubui
    # ports:
     # - 5000:80  currently UI module is not working in container, start standalone after container

  saphub.sapconnector:
    image: ${DOCKER_REGISTRY-}saphubsapconnector
    build:
      context: .
      dockerfile: src/SAPHub.SAPConnector/Dockerfile
    environment:
      - SAPHUB_BUS__TYPE=rabbitmq
      - SAPHUB_BUS__CONNECTIONSTRING=amqp://guest:guest@localhost
      - LD_LIBRARY_PATH=/app/
    depends_on:
      - rabbit
    network_mode: host


